name: Build Windows Executable

on:
  push:
    branches: [ main ]

jobs:
  build:
    runs-on: windows-latest

    steps:
    - name: Checkout repository
      uses: actions/checkout@v4

    - name: Set up Python
      uses: actions/setup-python@v4
      with:
        python-version: '3.10'

    - name: Verify resnet50.xml exists
      run: |
        if (-not (Test-Path -Path "resnet50.xml")) {
          Write-Host "❌ Error: resnet50.xml not found in root directory!"
          Exit 1
        }

    - name: Install dependencies
      run: |
        pip install -r requirements.txt

    - name: Build EXE with PyInstaller
      run: |
        pyinstaller --onefile --windowed --name "CaptchaSolver" --add-data "resnet50.xml;." main.py

    - name: Copy Model File to Dist
      run: |
        Copy-Item -Path "resnet50.xml" -Destination "dist/resnet50.xml" -Force

    - name: Upload Artifact
      uses: actions/upload-artifact@v4
      with:
        name: CaptchaSolver-Package
        path: |
          dist/CaptchaSolver.exe
          dist/resnet50.xml
